### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### getMember
GET localhost:8080/members/baek

### getProject
GET localhost:8080/projects/black&white