### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### getMember
GET localhost:8080/members/baek

### getMember error
GET localhost:8080/members/no

### getProject
GET localhost:8080/projects/black&white

### getProject error
GET localhost:8080/projects/no

### 새 유저 등록 jsj
POST localhost:8080/members
Content-Type: application/json

{
  "id": "jsj",
  "age": 25,
  "name": "조승주"
}

### jsj 유저 조회
GET localhost:8080/members/jsj

### 새 프로젝트 생성 nhn
POST localhost:8080/projects
Content-Type: application/json

{
  "code": "nhn",
  "localDate": "2024-12-25",
  "type": "PRIVATE"
}

### 프로젝트 nhn 조회
GET localhost:8080/projects/nhn

### 모든 멤버 리스트 조회
GET localhost:8080/membersAll

### 모든 프로젝트 리스트 조회
GET localhost:8080/projectsAll

### 멤버 리스트 페이지 테스트
GET localhost:8080/membersAll?page=1&size=1